### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by brianamarie** [githubschool/test-nov-30#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by githubstudent** [comment]
![2016-06-16_13_42_46](https://user-images.githubusercontent.com/1142544/49276596-3d397600-f47f-11e8-88b2-c43e9f815af2.gif)

**Comment by githubstudent** [comment]
cc @allthedoll @beardofedu

**Comment by billyyumyum2x2** [comment]
![20180828_151656](https://user-images.githubusercontent.com/17241061/49276732-999c9580-f47f-11e8-82d1-d8a33e4defd8.jpg)
